spring:
#  application:
#    name: my-service
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name:

eureka:
  client:
    healthcheck.enabled: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/v2

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG