spring:
  application:
    name: store-web

  jackson:
    serialization.write-dates-as-timestamps: false

eureka:
  client:
    healthcheck.enabled: true
    serviceUrl:
      defaultZone: ${SERVICES_REGISTRY}